const rtoDetails = [
	{name : "Madhya Pradesh", value: "MP-01"},
	{name : "Madhya Pradesh", value: "MP-02"},
	{name : "Madhya Pradesh", value: "MP-03"},
	{name : "Bhopal", value: "MP-04"},
	{name : "Hoshangabad", value: "MP-05"},
	{name : "Morena", value: "MP-06"},
	{name : "Gwalior", value: "MP-07"},
	{name : "Guna", value: "MP-08"},
	{name : "Indore", value: "MP-09"},
	{name : "Khargone", value: "MP-10"},
	{name : "Dhar", value: "MP-11"},
	{name : "Khandwa", value: "MP-12"},
	{name : "Ujjain", value: "MP-13"},
	{name : "Mandsaur", value: "MP-14"},
	{name : "Sagar", value: "MP-15"},
	{name : "Chhatarpur", value: "MP-16"},
	{name : "Rewa", value: "MP-17"},
	{name : "Shahdol", value: "MP-18"},
	{name : "Satna", value: "MP-19"},
	{name : "Jabalpur", value: "MP-20"},
	{name : "Katni", value: "MP-21"},
	{name : "Seoni", value: "MP-22"},
	{name : "Raipur", value: "MP-23"},
	{name : "Durg", value: "MP-24"},
	{name : "Jagdalpur", value: "MP-25"},
	{name : "Bilaspur", value: "MP-26"},
	{name : "Ambikapur", value: "MP-27"},
	{name : "Chhindwara", value: "MP-28"},
	{name : "Rajnandgaon", value: "MP-29"},
	{name : "Bhind", value: "MP-30"},	
	{name : "Sheopur", value: "MP-31"},
	{name : "Datia", value: "MP-32"},
	{name : "Shivpuri", value: "MP-33"},
	{name : "Damoh", value: "MP-34"},
	{name : "Panna", value: "MP-35"},
	{name : "Tikamgarh", value: "MP-36"},
	{name : "Sehore", value: "MP-37"},
	{name : "Raisen", value: "MP-38"},
	{name : "Rajgarh", value: "MP-39"},
	{name : "Vidisha", value: "MP-40"},
	{name : "Dewas", value: "MP-41"},
	{name : "Shajapur", value: "MP-42"},
	{name : "Ratlam", value: "MP-43"},
	{name : "Neemuch", value: "MP-44"},
	{name : "Jhabua", value: "MP-45"},
	{name : "Barwani", value: "MP-46"},
	{name : "Harda", value: "MP-47"},
	{name : "Betul", value: "MP-48"},
	{name : "Narsinghpur", value: "MP-49"},
	{name : "Balaghat", value: "MP-50"},
	{name : "Mandla", value: "MP-51"},
	{name : "Dindori", value: "MP-52"},
	{name : "Sidhi", value: "MP-53"},
	{name : "Umaria", value: "MP-54"},
	{name : "Anuppur", value: "MP-65"},
	{name : "Singrauli", value: "MP-66"},
	{name : "Ashoknagar", value: "MP-67"},
	{name : "Burhanpur", value: "MP-68"},
	{name : "Alirajpur", value: "MP-69"},
	{name : "Agar", value: "MP-70"},	
]
// const 